#!/bin/bash

# Install IBM CLoud CLI with container-service plugin
set -e
while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
      --target-platform)
    TARGET_PLATFORM="$2"
    ;;
      --ibmcli-version)
    IBMCLI_VERSION="$2"
    ;;
        *)
        # unknown option, use as additional params directly to docker
        EXTRA_PARAMS="$EXTRA_PARAMS $key $2"
        ;;
    esac
    shift
    shift
done
#fallback to amd64 if architecture not defined
if [[ "$TARGET_PLATFORM" == "" ]]
  then TARGET_PLATFORM=amd64
fi
#fallback to 2.38.1 if version not defined
if [[ "$IBMCLI_VERSION" == "" ]]
  then IBMCLI_VERSION=2.38.1
fi

CLI_VERSION=${IBMCLI_VERSION}
wget -q https://download.clis.cloud.ibm.com/ibm-cloud-cli/${CLI_VERSION}/IBM_Cloud_CLI_${CLI_VERSION}_${TARGET_PLATFORM}.tar.gz

tar -xzf IBM_Cloud_CLI_${CLI_VERSION}_${TARGET_PLATFORM}.tar.gz
mv Bluemix_CLI/bin/ibmcloud /usr/local/bin/
rm -rf Bluemix_CLI IBM_Cloud_CLI_${CLI_VERSION}_${TARGET_PLATFORM}.tar.gz
ibmcloud plugin repo-plugins -r 'IBM Cloud'
ibmcloud plugin install container-registry
ibmcloud plugin install secrets-manager
# Plugin not supported in ppc64le (Could not find compatible binary to install for plug-in container-service[kubernetes-service/ks]
if [[ "$TARGET_PLATFORM" != "ppc64le" ]]
  then
  ibmcloud plugin install container-service
fi

# We don't want remove the plugins (in .bluemix/plugins) only the configuration file generated by the above actions
rm /app-root/.bluemix/config.json

# Disable version check on login
ibmcloud config --check-version=false

# Fix up permissions so that the group has the same permissions as the (root) user
chown -R sterling:root /app-root/.bluemix
chmod -R g=u /app-root/.bluemix

echo "Ibmcloud version:"
ibmcloud version
